# -*- coding: utf-8 -*-
"""Improved RMAB policy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qO_VnRFbPAntX29-HiK_f0kZbtqS0xZ
"""

!pip install lightgbm

import pickle, joblib, json, time
import numpy as np, pandas as pd
from pathlib import Path
from scipy.special import softmax
import matplotlib.pyplot as plt

BASE = Path("/content")
RMAB_PKL = BASE / "rmab_sequences.pkl"
BUNDLE_PKL = BASE / "policy_bundle.pkl"
CLEAN_CSV = BASE / "final_traj_clean_training_heart_v2_sorted_imputed.csv"


for p in (RMAB_PKL, BUNDLE_PKL, CLEAN_CSV):
    print(p.name, "exists:", p.exists())

def load_bundle(bundle_pkl=BUNDLE_PKL, rmab_pkl=RMAB_PKL):
    bundle = joblib.load(bundle_pkl)
    sequences = pickle.load(open(rmab_pkl, "rb"))["sequences"]
    return bundle, sequences

def compute_wis_ess_for_seqdict(seq_dict, bundle, cfg, gamma=0.95):
    behavior = bundle["models"]["behavior"]
    q_models = bundle["models"]["q_models"]
    state_cols = bundle["state_cols"]
    actions = sorted(list(q_models.keys()))
    weights, returns = [], []
    for _, seq in seq_dict.items():
        S, A, R = np.asarray(seq["S"]), np.asarray(seq["A"], int), np.asarray(seq["R"], float)
        X = pd.DataFrame(S, columns=state_cols).fillna(0.0)
        b = behavior.predict_proba(X)                    # (T,K)
        q = np.vstack([q_models[a].predict(X.values) for a in actions]).T
        pi = softmax(q / cfg["temp"], axis=1)
        if cfg.get("tau", 0.0) > 0:
            mask = b < cfg["tau"]
            pi = np.where(mask, 0.0, pi)
            s = pi.sum(1, keepdims=True)
            pi = np.where(s > 0, pi/s, b)
        pi_mix = (1.0 - cfg["alpha"]) * b + cfg["alpha"] * pi
        idx = np.arange(len(A))
        b_sel = np.maximum(b[idx, A], 1e-12)
        pi_sel = np.maximum(pi_mix[idx, A], 1e-12)
        ratio = np.clip(pi_sel / b_sel, 0.0, cfg.get("clip", 3.0))
        w = float(np.prod(ratio))
        ret = float((gamma ** np.arange(len(R)) * R).sum())
        weights.append(w); returns.append(ret)
    W = np.array(weights, dtype=float); Rv = np.array(returns, dtype=float)
    wis = float((W * Rv).sum() / (W.sum() + 1e-12))
    ess = float((W.sum()**2) / (np.sum(W**2) + 1e-12)) if W.size>0 else 0.0
    behavior_value = float(Rv.mean())
    return {"W":W, "R":Rv, "wis":wis, "ess":ess, "behavior":behavior_value}

def bootstrap_ci(W, Rv, B=1000, seed=42):
    rng = np.random.default_rng(seed)
    n = len(W)
    vals = np.empty(B)
    for i in range(B):
        idx = rng.integers(0, n, n)
        w_s = W[idx]; r_s = Rv[idx]
        vals[i] = (w_s * r_s).sum() / (w_s.sum() + 1e-12)
    return np.percentile(vals, [2.5, 97.5]), vals

bundle, sequences = load_bundle()

chosen = {}
for (hid, aug) in sequences.keys():
    if hid not in chosen or aug < chosen[hid][0]:
        chosen[hid] = (aug, sequences[(hid, aug)])
seq_dedup = { (hid, aug): seq for hid,(aug,seq) in chosen.items() }

CFG = {"temp":0.25, "alpha":0.30, "tau":0.01, "clip":2.5}
res = compute_wis_ess_for_seqdict(seq_dedup, bundle, CFG)
print("n_dedup:", len(seq_dedup), "WIS:", res["wis"], "ESS:", res["ess"], "behavior:", res["behavior"])

(ci_low, ci_high), bs = bootstrap_ci(res["W"], res["R"], B=1000)
print("Bootstrap CI:", ci_low, ci_high)

# weight histogram
plt.hist(np.log1p(res["W"]), bins=60)
plt.title("log1p(W) histogram"); plt.show()

# cumulative weight share
sorted_idx = np.argsort(res["W"])[::-1]
cumw = np.cumsum(res["W"][sorted_idx]) / (res["W"].sum()+1e-12)
pct_traj = np.arange(1, len(res["W"])+1) / len(res["W"]) * 100
plt.plot(pct_traj, cumw*100); plt.axhline(50, linestyle='--'); plt.axhline(90, linestyle='--')
plt.xlabel("top x% trajectories"); plt.ylabel("cumulative weight %"); plt.show()

# top offending trajectories
topk = 20
top_idx = sorted_idx[:topk]
for i in top_idx:
    print(f"Rank {i}: weight={res['W'][i]:.3e}, ret={res['R'][i]:.3f}")

import numpy as np, pandas as pd
from scipy.special import softmax
import matplotlib.pyplot as plt




res = compute_wis_ess_for_seqdict(seq_dedup, bundle, CFG)
W, R = res["W"], res["R"]
n = len(W)
sorted_idx = np.argsort(W)[::-1]
topk = 20
print("n:", n, "ESS:", res["ess"], "WIS:", res["wis"], "behavior:", res["behavior"])


for rank, idx in enumerate(sorted_idx[:topk], start=1):
    seq_key = list(seq_dedup.keys())[idx]
    seq = list(seq_dedup.values())[idx]
    print(f"Rank {rank} idx={idx} key={seq_key} weight={W[idx]:.3e} ret={R[idx]:.3f} len={len(seq['A'])}")


def per_timestep_trace(seq, bundle, cfg):
    S, A = np.asarray(seq["S"]), np.asarray(seq["A"], int)
    X = pd.DataFrame(S, columns=bundle['state_cols']).fillna(0.0)
    b = bundle['models']['behavior'].predict_proba(X)
    actions = sorted(list(bundle['models']['q_models'].keys()))
    q = np.vstack([bundle['models']['q_models'][a].predict(X.values) for a in actions]).T
    pi = softmax(q / cfg['temp'], axis=1)

    if cfg.get('tau',0.0)>0:
        mask = b < cfg['tau']
        pi = np.where(mask, 0.0, pi)
        s = pi.sum(1, keepdims=True)
        pi = np.where(s>0, pi/s, b)
    pi_mix = (1.0 - cfg['alpha']) * b + cfg['alpha'] * pi
    idx = np.arange(len(A))
    b_sel = np.maximum(b[idx, A], 1e-12)
    pi_sel = np.maximum(pi_mix[idx, A], 1e-12)
    ratios = pi_sel / b_sel
    return ratios, b_sel, pi_sel


plt.figure(figsize=(12,8))
for i, idx in enumerate(sorted_idx[:6]):
    ratios, bsel, pisel = per_timestep_trace(list(seq_dedup.values())[idx], bundle, CFG)
    plt.subplot(3,2,i+1)
    plt.plot(np.log10(ratios+1e-12), marker='o', linewidth=1)
    plt.title(f"Top {i+1} idx={idx} weight={W[idx]:.1e} ret={R[idx]:.3f}")
    plt.axhline(np.log10(2), color='r', linestyle='--')
plt.tight_layout(); plt.show()

def recompute_after_drop(seq_dedup, bundle, cfg, drop_frac=0.01):

    res = compute_wis_ess_for_seqdict(seq_dedup, bundle, cfg)
    W = res['W']; R = res['R']
    n = len(W)
    k = max(1, int(n * drop_frac))
    drop_idx = np.argsort(W)[::-1][:k]
    keep_mask = np.ones(n, bool); keep_mask[drop_idx]=False
    Wk, Rk = W[keep_mask], R[keep_mask]
    wis_k = float((Wk * Rk).sum() / (Wk.sum()+1e-12))
    return {"drop_frac":drop_frac, "k":k, "wis":wis_k, "orig_wis":res['wis']}

for df in [0.01, 0.05, 0.10]:
    print(recompute_after_drop(seq_dedup, bundle, CFG, df))

# Precompute b (behavior probs) and q_logits for all timesteps.
# Assumptions: seq_dedup is a dict-like of sequences with keys and values
# seq = {'S': list_of_state_vectors, 'A': list_of_actions, 'R': list_of_rewards}
# bundle contains: bundle['models']['behavior'], bundle['models']['q_models'], bundle['state_cols']

import numpy as np, pandas as pd
from scipy.special import softmax
from tqdm.auto import tqdm
import joblib

# Build lists
seq_keys = list(seq_dedup.keys())
seq_list = [seq_dedup[k] for k in seq_keys]
n_seq = len(seq_list)

# Flatten timesteps into single arrays
all_states = []
all_actions = []
all_rewards = []
seq_starts = np.zeros(n_seq, dtype=np.int64)
for i, seq in enumerate(seq_list):
    seq_starts[i] = len(all_actions)
    all_states.extend(seq['S'])
    all_actions.extend(seq['A'])
    all_rewards.extend(seq['R'])
all_states = np.asarray(all_states)           # (total_T, state_dim)
all_actions = np.asarray(all_actions, int)   # (total_T,)
all_rewards = np.asarray(all_rewards, float) # (total_T,)

# Predict behavior probabilities once (for all timesteps)
# Behavior model returns K probs per timestep
state_df = pd.DataFrame(all_states, columns=bundle['state_cols']).fillna(0.0)
behavior = bundle['models']['behavior']
b_all = behavior.predict_proba(state_df)     # shape (total_T, K)

# Predict Q logits / values for each action model once.
actions_sorted = sorted(list(bundle['models']['q_models'].keys()))
q_list = []
for a in actions_sorted:
    qm = bundle['models']['q_models'][a]
    q_pred = qm.predict(state_df.values)     # shape (total_T,)  (Q value / logit depending on model)
    q_list.append(q_pred)
q_all = np.vstack(q_list).T                 # shape (total_T, K)

# Build per-trajectory offsets & lengths
seq_lens = []
for i in range(n_seq):
    start = seq_starts[i]
    if i+1 < n_seq:
        end = seq_starts[i+1]
    else:
        end = all_actions.shape[0]
    seq_lens.append(end - start)
seq_lens = np.array(seq_lens, int)

# Save precomputed arrays for reuse
joblib.dump({'b_all': b_all, 'q_all': q_all, 'all_actions': all_actions,
             'all_rewards': all_rewards, 'seq_starts': seq_starts, 'seq_lens': seq_lens,
             'actions_sorted': actions_sorted}, 'precomp_ohe.joblib')
print("Precompute done: total timesteps =", all_actions.shape[0])

# Utilities for vectorized WIS/ESS computation across many configs
import numpy as np

def compute_wis_ess_vectorized(config, b_all, q_all, all_actions, seq_starts, seq_lens, gamma=0.95, clip=3.0):
    # config = {'alpha':..., 'tau':..., 'temp':...}
    alpha, tau, temp = config['alpha'], config['tau'], config['temp']
    # 1) compute pi (softmax across actions) from q_all / temp
    logits = q_all / (temp + 1e-12)
    pi = np.exp(logits - logits.max(axis=1, keepdims=True))
    pi = pi / (pi.sum(axis=1, keepdims=True) + 1e-12)   # (total_T, K)

    # 2) apply tau truncation: where b_all < tau, zero out pi and renormalize to b if zero
    if tau > 0:
        mask = (b_all < tau)       # boolean (total_T, K)
        # set pi to zero where mask True, but mask is per-action; we only want to zero actions whose b < tau
        pi = np.where(mask, 0.0, pi)
        s = pi.sum(axis=1, keepdims=True)
        # where s==0, fallback to b_all
        pi = np.where(s > 0, pi / (s + 1e-12), b_all)

    # 3) mix with behavior
    pi_mix = (1.0 - alpha) * b_all + alpha * pi

    # 4) select probabilities for executed actions
    idx = np.arange(all_actions.shape[0])
    b_sel = np.maximum(b_all[idx, all_actions], 1e-12)
    pi_sel = np.maximum(pi_mix[idx, all_actions], 1e-12)

    # 5) optional clipping: clip ratio to [1/clip, clip] if symmetric desired; original used upper clip
    ratio = pi_sel / b_sel
    ratio = np.minimum(ratio, clip)   # keep lower bound ~0
    log_ratio = np.log(ratio + 1e-12)

    # 6) sum log_ratio per-trajectory into logW for each trajectory
    # Use add.reduceat with seq_starts
    # create array of cumulative sums per timestep weight to split by seq_starts
    cumsum_logratio = np.add.reduceat(log_ratio, seq_starts)  # sum of log_ratios per seq
    # But add.reduceat with seq_starts expects proper indexing; ensure indexing covers all sequences
    # For safety, compute per-trajectory using loop over starts if this errors; but it's usually fast.

    # convert to W (exp)
    W = np.exp(cumsum_logratio)

    # 7) compute returns per trajectory fast (discounted)
    # Precompute prefix sums of discounted returns across flat array then reduceat
    # But easier: compute per-timestep discounted reward-to-go per trajectory is more work.
    # Simpler (vectorized): iterate per trajectory lengths but that's cheap compared to model predicts.
    # However, we can compute return-per-trajectory by grouping using the seq_starts/seq_lens:
    n_seq = len(seq_lens)
    Rv = np.empty(n_seq, dtype=float)
    ptr = 0
    for i in range(n_seq):
        L = seq_lens[i]
        r = all_rewards[ptr:ptr+L]
        discounts = (gamma ** np.arange(L))
        Rv[i] = (discounts * r).sum()
        ptr += L

    # 8) WIS and ESS
    W = np.clip(W, 0.0, 1e12)
    wis = float((W * Rv).sum() / (W.sum() + 1e-12))
    ess = float((W.sum()**2) / (np.sum(W**2) + 1e-12))
    return {'W': W, 'R': Rv, 'wis': wis, 'ess': ess}

# Example use for one config:
cfg = {'alpha':0.3, 'tau':0.01, 'temp':0.25, 'clip':2.5}
out = compute_wis_ess_vectorized(cfg, b_all, q_all, all_actions, seq_starts, seq_lens)
print("wis, ess:", out['wis'], out['ess'])

from joblib import Parallel, delayed
import numpy as np

def bootstrap_single_seed(W, Rv, B, seed):
    rng = np.random.default_rng(seed)
    n = len(W)
    vals = []
    for _ in range(B):
        idx = rng.integers(0, n, n)
        w_s = W[idx]; r_s = Rv[idx]
        vals.append((w_s * r_s).sum() / (w_s.sum() + 1e-12))
    return np.array(vals)


def bootstrap_ci_parallel(W, Rv, B=200, n_jobs=8):
    seeds = list(range(n_jobs))
    parts = [B // n_jobs] * n_jobs
    results = Parallel(n_jobs=n_jobs)(delayed(bootstrap_single_seed)(W, Rv, parts[i], seeds[i]) for i in range(n_jobs))
    allvals = np.concatenate(results)
    return np.percentile(allvals, [2.5, 97.5]), allvals

logW = np.log(out['W'] + 1e-12)
print("mean logW:", logW.mean())
print("std logW:", logW.std())
print("max logW:", logW.max())

print("Top 10 weights:", np.sort(out['W'])[-10:])



"""##**DR**"""

import numpy as np

def evaluate_policy_DR(
    config,
    b_all,
    q_all,
    all_actions,
    all_rewards,
    seq_starts,
    seq_lens,
    gamma=0.95,
):
    alpha = config['alpha']
    tau   = config['tau']
    temp  = config['temp']
    clip  = config.get('clip', 2.5)

    total_T, K = b_all.shape

    # -------------------------
    # 1) Target Policy π
    # -------------------------
    logits = q_all / (temp + 1e-12)
    pi = np.exp(logits - logits.max(axis=1, keepdims=True))
    pi /= (pi.sum(axis=1, keepdims=True) + 1e-12)

    if tau > 0:
        mask = (b_all < tau)
        pi = np.where(mask, 0.0, pi)
        s = pi.sum(axis=1, keepdims=True)
        pi = np.where(s > 0, pi/(s+1e-12), b_all)

    pi_mix = (1 - alpha)*b_all + alpha*pi

    # -------------------------
    # 2) Per-step ratios
    # -------------------------
    idx = np.arange(total_T)
    b_sel  = np.maximum(b_all[idx, all_actions], 1e-12)
    pi_sel = np.maximum(pi_mix[idx, all_actions], 1e-12)

    ratio = pi_sel / b_sel
    ratio = np.minimum(ratio, clip)

    # -------------------------
    # 3) Precompute V(s)
    # -------------------------
    V_s = np.sum(pi_mix * q_all, axis=1)

    # -------------------------
    # 4) Per-trajectory loop
    # -------------------------
    n_seq = len(seq_lens)
    WIS_vals = np.zeros(n_seq)
    DR_vals  = np.zeros(n_seq)
    BEHAV_vals = np.zeros(n_seq)

    ptr = 0
    for i in range(n_seq):
        L = seq_lens[i]

        rho_cum = 1.0
        rho_prev = 1.0
        wis_return = 0.0
        dr_return  = 0.0
        beh_return = 0.0

        for t in range(L):
            r = all_rewards[ptr+t]
            discount = gamma**t

            # Behavior return
            beh_return += discount * r

            # WIS
            rho_cum *= ratio[ptr+t]
            wis_return += discount * rho_cum * r

            # DR
            Q_sa = q_all[ptr+t, all_actions[ptr+t]]

            dr_return += discount * (
                rho_cum * (r - Q_sa)
                + rho_prev * V_s[ptr+t]
            )

            rho_prev = rho_cum

        WIS_vals[i] = wis_return
        DR_vals[i]  = dr_return
        BEHAV_vals[i] = beh_return

        ptr += L


    behavior_value = BEHAV_vals.mean()

    W = np.ones_like(WIS_vals)
    wis_value = WIS_vals.mean()

    dr_value = DR_vals.mean()



    ptr = 0
    traj_weights = np.zeros(n_seq)
    for i in range(n_seq):
        L = seq_lens[i]
        traj_weights[i] = np.prod(ratio[ptr:ptr+L])
        ptr += L

    ess = (traj_weights.sum()**2) / (np.sum(traj_weights**2) + 1e-12)

    return {
        "behavior": behavior_value,
        "wis": wis_value,
        "dr": dr_value,
        "ess": ess,
        "traj_weights": traj_weights,
        "WIS_vals": WIS_vals,
        "DR_vals": DR_vals
    }

def bootstrap_ci(values, B=1000, seed=0):
    rng = np.random.default_rng(seed)
    n = len(values)
    samples = []
    for _ in range(B):
        idx = rng.integers(0, n, n)
        samples.append(values[idx].mean())
    samples = np.array(samples)
    return np.percentile(samples, [2.5, 97.5])

config = {
    "alpha": 0.2,
    "tau": 0.02,
    "temp": 0.4,
    "clip": 2.0
}

results = evaluate_policy_DR(
    config,
    b_all,
    q_all,
    all_actions,
    all_rewards,
    seq_starts,
    seq_lens
)

print("Behavior:", results["behavior"])
print("WIS:", results["wis"])
print("DR:", results["dr"])
print("ESS:", results["ess"])

print("WIS CI:", bootstrap_ci(results["WIS_vals"]))
print("DR CI:", bootstrap_ci(results["DR_vals"]))

config = {
    "alpha": 0.1,
    "tau": 0.05,
    "temp": 0.5,
    "clip": 1.5
}

results = evaluate_policy_DR(
    config,
    b_all,
    q_all,
    all_actions,
    all_rewards,
    seq_starts,
    seq_lens
)

print("Behavior:", results["behavior"])
print("WIS:", results["wis"])
print("DR:", results["dr"])
print("ESS:", results["ess"])

print("WIS CI:", bootstrap_ci(results["WIS_vals"]))
print("DR CI:", bootstrap_ci(results["DR_vals"]))



"""###**Improving Policy**"""

from sklearn.ensemble import RandomForestRegressor
import numpy as np
import joblib

def prepare_fqe_data(seq_list, gamma=0.95):

    S, A, R, S2, Done = [], [], [], [], []
    for seq in seq_list:
        states = np.asarray(seq['S'])
        actions = np.asarray(seq['A'], int)
        rewards = np.asarray(seq['R'], float)
        L = len(actions)
        for t in range(L):
            S.append(states[t])
            A.append(actions[t])
            R.append(rewards[t])
            if t+1 < L:
                S2.append(states[t+1])
                Done.append(0)
            else:
                S2.append(np.zeros(states.shape[1]))
                Done.append(1)
    return np.vstack(S), np.array(A), np.array(R), np.vstack(S2), np.array(Done)


S, A, R, S2, Done = prepare_fqe_data(seq_list)


n_actions = len(actions_sorted)


Q_models = [RandomForestRegressor(n_estimators=100, max_depth=8, random_state=0) for _ in range(n_actions)]


Q_vals_next = np.zeros((S.shape[0], n_actions))

n_iters = 20
for it in range(n_iters):


    next_max = Q_vals_next.max(axis=1) * (1 - Done)
    targets = R + 0.95 * next_max


    for a in range(n_actions):
        idx = (A == a)
        if idx.sum() == 0:
            continue
        X_fit = S[idx]
        y_fit = targets[idx]
        Q_models[a].fit(X_fit, y_fit)


    for a in range(n_actions):
        Q_vals_next[:, a] = Q_models[a].predict(S)



joblib.dump(Q_models, "fqe_q_models.joblib")

import joblib
fqe_q_models = joblib.load("fqe_q_models.joblib")

q_all_fqe = np.zeros_like(q_all)

for a in range(len(fqe_q_models)):
    q_all_fqe[:, a] = fqe_q_models[a].predict(state_df.values)

config = {
    "alpha": 0.1,
    "tau": 0.03,
    "temp": 0.5,
    "clip": 1.5
}

results_fqe = evaluate_policy_DR(
    config,
    b_all,
    q_all_fqe,
    all_actions,
    all_rewards,
    seq_starts,
    seq_lens
)

print("Behavior:", results_fqe["behavior"])
print("WIS:", results_fqe["wis"])
print("DR:", results_fqe["dr"])
print("ESS:", results_fqe["ess"])

print("WIS CI:", bootstrap_ci(results_fqe["WIS_vals"]))
print("DR CI:", bootstrap_ci(results_fqe["DR_vals"]))

print("Old Q mean:", q_all.mean())
print("FQE Q mean:", q_all_fqe.mean())

print("Old Q min/max:", q_all.min(), q_all.max())
print("FQE Q min/max:", q_all_fqe.min(), q_all_fqe.max())



"""###**Correct FQE Implementation**"""

import numpy as np

def prepare_fqe_data(seq_list):
    S, A, R, S2, Done = [], [], [], [], []

    for seq in seq_list:
        states = np.asarray(seq['S'])
        actions = np.asarray(seq['A'], int)
        rewards = np.asarray(seq['R'], float)
        L = len(actions)

        for t in range(L):
            S.append(states[t])
            A.append(actions[t])
            R.append(rewards[t])

            if t+1 < L:
                S2.append(states[t+1])
                Done.append(0)
            else:
                S2.append(states[t])
                Done.append(1)

    return (
        np.vstack(S),
        np.array(A),
        np.array(R),
        np.vstack(S2),
        np.array(Done)
    )

S, A, R, S2, Done = prepare_fqe_data(seq_list)

from sklearn.ensemble import RandomForestRegressor
from scipy.special import softmax

def train_fqe_policy_backup(
    S, A, R, S2, Done,
    n_actions,
    gamma=0.95,
    temp=0.5,
    n_iters=20
):


    Q_models = [
        RandomForestRegressor(n_estimators=100, max_depth=8, random_state=0)
        for _ in range(n_actions)
    ]


    Q_next = np.zeros((S.shape[0], n_actions))

    for it in range(n_iters):

        # ---- compute policy π from current Q ----
        logits = Q_next / (temp + 1e-12)
        pi_next = softmax(logits, axis=1)

        # ---- compute V(s') under π ----
        V_next = np.sum(pi_next * Q_next, axis=1)

        # ---- compute Bellman target ----
        targets = R + gamma * V_next * (1 - Done)

        # ---- fit per-action regressors ----
        for a in range(n_actions):
            idx = (A == a)
            if idx.sum() == 0:
                continue

            Q_models[a].fit(S[idx], targets[idx])

        # ---- update Q_next for next iteration ----
        for a in range(n_actions):
            Q_next[:, a] = Q_models[a].predict(S2)

        print(f"FQE iteration {it+1}/{n_iters} done.")

    return Q_models

n_actions = len(actions_sorted)

fqe_models_correct = train_fqe_policy_backup(
    S, A, R, S2, Done,
    n_actions=n_actions,
    gamma=0.95,
    temp=0.5,
    n_iters=20
)

import joblib
joblib.dump(fqe_models_correct, "fqe_correct_policy_backup.joblib")

q_all_fqe_correct = np.zeros_like(q_all)

for a in range(n_actions):
    q_all_fqe_correct[:, a] = fqe_models_correct[a].predict(state_df.values)

print("Correct FQE Q mean:", q_all_fqe_correct.mean())
print("Correct FQE Q min/max:", q_all_fqe_correct.min(), q_all_fqe_correct.max())

config = {
    "alpha": 0.1,
    "tau": 0.03,
    "temp": 0.5,
    "clip": 1.5
}

results_correct = evaluate_policy_DR(
    config,
    b_all,
    q_all_fqe_correct,
    all_actions,
    all_rewards,
    seq_starts,
    seq_lens
)

print("Behavior:", results_correct["behavior"])
print("DR:", results_correct["dr"])
print("ESS:", results_correct["ess"])
print("DR CI:", bootstrap_ci(results_correct["DR_vals"]))

import itertools
import pandas as pd


alphas = [0.05, 0.1, 0.2]
taus   = [0.02, 0.05]
temps  = [0.4, 0.5, 0.6]
clip   = 1.5

rows = []

for alpha, tau, temp in itertools.product(alphas, taus, temps):

    config = {
        "alpha": alpha,
        "tau": tau,
        "temp": temp,
        "clip": clip
    }

    res = evaluate_policy_DR(
        config,
        b_all,
        q_all_fqe_correct,
        all_actions,
        all_rewards,
        seq_starts,
        seq_lens
    )

    ci_low, ci_high = bootstrap_ci(res["DR_vals"], B=500)

    rows.append({
        "alpha": alpha,
        "tau": tau,
        "temp": temp,
        "DR": res["dr"],
        "CI_low": ci_low,
        "CI_high": ci_high,
        "ESS": res["ess"]
    })

df_results = pd.DataFrame(rows)

print("Behavior value:", results_correct["behavior"])
df_results.sort_values("DR", ascending=False)

import numpy as np


DR_vals = results_correct["DR_vals"]

n = len(DR_vals)
k = int(0.05 * n)

sorted_idx = np.argsort(DR_vals)[::-1]
keep_idx = sorted_idx[k:]

DR_removed = DR_vals[keep_idx].mean()

print("Original DR:", results_correct["dr"])
print("DR after removing top 5%:", DR_removed)
print("Difference:", results_correct["dr"] - DR_removed)

print(state_df.columns.tolist())

import numpy as np


lactate_idx = state_df.columns.get_loc("lactate")


baseline_lactate = np.array([
    seq['S'][0][lactate_idx]
    for seq in seq_list
])


median_lactate = np.median(baseline_lactate)

low_idx  = baseline_lactate <= median_lactate
high_idx = baseline_lactate > median_lactate

print("Median baseline lactate:", median_lactate)
print("Low group size:", low_idx.sum())
print("High group size:", high_idx.sum())

DR_vals = results_correct["DR_vals"]

# recompute behavior per trajectory
def compute_behavior_per_traj():
    vals = []
    ptr = 0
    for L in seq_lens:
        r = all_rewards[ptr:ptr+L]
        discounts = 0.95 ** np.arange(L)
        vals.append((discounts * r).sum())
        ptr += L
    return np.array(vals)

behavior_vals = compute_behavior_per_traj()

print("\nLOW LACTATE GROUP")
print("Behavior:", behavior_vals[low_idx].mean())
print("DR:", DR_vals[low_idx].mean())

print("\nHIGH LACTATE GROUP")
print("Behavior:", behavior_vals[high_idx].mean())
print("DR:", DR_vals[high_idx].mean())

def bootstrap_group(values, mask, B=500):
    rng = np.random.default_rng(0)
    group_vals = values[mask]
    n = len(group_vals)
    samples = []
    for _ in range(B):
        idx = rng.integers(0, n, n)
        samples.append(group_vals[idx].mean())
    return np.percentile(samples, [2.5, 97.5])

print("\nLOW Lactate DR CI:", bootstrap_group(DR_vals, low_idx))
print("HIGH Lactate DR CI:", bootstrap_group(DR_vals, high_idx))



"""#**Final Results**"""

import matplotlib.pyplot as plt
import numpy as np

behavior = results_correct["behavior"]
dr_mean = results_correct["dr"]
ci_low, ci_high = bootstrap_ci(results_correct["DR_vals"])

plt.figure()
plt.bar(["Behavior", "Proposed Policy (DR)"],
        [behavior, dr_mean])

plt.errorbar(1, dr_mean,
             yerr=[[dr_mean - ci_low], [ci_high - dr_mean]],
             fmt='o')

plt.ylabel("Expected Discounted Return")
plt.title("Performance Comparison under Doubly Robust Evaluation")
plt.show()

ess = results_correct["ess"]

plt.figure()
plt.bar(["ESS"], [ess])
plt.ylabel("Effective Sample Size")
plt.title("Effective Sample Size under DR Evaluation")
plt.show()

low_behavior = behavior_vals[low_idx].mean()
high_behavior = behavior_vals[high_idx].mean()

low_dr = DR_vals[low_idx].mean()
high_dr = DR_vals[high_idx].mean()

low_ci = bootstrap_group(DR_vals, low_idx)
high_ci = bootstrap_group(DR_vals, high_idx)

groups = ["Low Lactate", "High Lactate"]
behavior_vals_plot = [low_behavior, high_behavior]
dr_vals_plot = [low_dr, high_dr]

x = np.arange(len(groups))

plt.figure()
plt.bar(x - 0.2, behavior_vals_plot, width=0.4, label="Clinician")
plt.bar(x + 0.2, dr_vals_plot, width=0.4, label="Proposed Policy")

plt.errorbar(x + 0.2, dr_vals_plot,
             yerr=[[dr_vals_plot[i] - low_ci[0] if i==0 else dr_vals_plot[i] - high_ci[0]
                    for i in range(2)],
                   [low_ci[1] - dr_vals_plot[0] if i==0 else high_ci[1] - dr_vals_plot[1]
                    for i in range(2)]],
             fmt='o')

plt.xticks(x, groups)
plt.ylabel("Expected Discounted Return")
plt.title("Subgroup Performance by Baseline Lactate")
plt.legend()
plt.show()

plt.figure()
plt.hist(DR_vals, bins=50)
plt.axvline(behavior, linestyle='--')
plt.title("Distribution of DR Estimates Across Trajectories")
plt.xlabel("DR Value")
plt.ylabel("Count")
plt.show()

# clinician action frequencies
clin_actions = all_actions
clin_counts = np.bincount(clin_actions)
clin_freq = clin_counts / clin_counts.sum()

# policy action probabilities (average across states)
from scipy.special import softmax

logits = q_all_fqe_correct / 0.5
pi = softmax(logits, axis=1)
pi_mix = (1 - 0.1) * b_all + 0.1 * pi
policy_freq = pi_mix.mean(axis=0)

x = np.arange(len(clin_freq))

plt.figure()
plt.bar(x - 0.2, clin_freq, width=0.4, label="Clinician")
plt.bar(x + 0.2, policy_freq, width=0.4, label="Proposed Policy")

plt.xlabel("Action Index")
plt.ylabel("Action Frequency")
plt.title("Treatment Distribution Comparison")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.style.use("default")

plt.rcParams.update({
    "figure.figsize": (6,4),
    "font.size": 12,
    "axes.titlesize": 13,
    "axes.labelsize": 12,
    "legend.fontsize": 11,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "axes.spines.top": False,
    "axes.spines.right": False
})

behavior = results_correct["behavior"]
dr_mean = results_correct["dr"]
ci_low, ci_high = bootstrap_ci(results_correct["DR_vals"], B=1000)

plt.figure()

bars = plt.bar(["Clinician", "Proposed Policy"],
               [behavior, dr_mean])

plt.errorbar(1, dr_mean,
             yerr=[[dr_mean - ci_low], [ci_high - dr_mean]],
             fmt='o', capsize=5)

plt.ylabel("Expected Discounted Return")
plt.title("Performance under Doubly Robust Evaluation")

plt.tight_layout()
plt.savefig("figure_main_performance.pdf", format="pdf")
plt.show()

groups = ["Low Lactate", "High Lactate"]
behavior_vals_plot = [low_behavior, high_behavior]
dr_vals_plot = [low_dr, high_dr]

low_ci = bootstrap_group(DR_vals, low_idx, B=1000)
high_ci = bootstrap_group(DR_vals, high_idx, B=1000)

ci_lows = [low_ci[0], high_ci[0]]
ci_highs = [low_ci[1], high_ci[1]]

x = np.arange(len(groups))
width = 0.35

plt.figure()

plt.bar(x - width/2, behavior_vals_plot, width, label="Clinician")
plt.bar(x + width/2, dr_vals_plot, width, label="Proposed Policy")

plt.errorbar(x + width/2, dr_vals_plot,
             yerr=[np.array(dr_vals_plot)-np.array(ci_lows),
                   np.array(ci_highs)-np.array(dr_vals_plot)],
             fmt='o', capsize=5)

plt.xticks(x, groups)
plt.ylabel("Expected Discounted Return")
plt.title("Subgroup Analysis by Baseline Lactate")
plt.legend()

plt.tight_layout()
plt.savefig("figure_subgroup.pdf", format="pdf")
plt.show()

from scipy.special import softmax


logits = q_all_fqe_correct / 0.5
pi = softmax(logits, axis=1)
pi_mix = (1 - 0.1) * b_all + 0.1 * pi

clin_counts = np.bincount(all_actions)
clin_freq = clin_counts / clin_counts.sum()
policy_freq = pi_mix.mean(axis=0)

x = np.arange(len(clin_freq))
width = 0.35

plt.figure()

plt.bar(x - width/2, clin_freq, width, label="Clinician")
plt.bar(x + width/2, policy_freq, width, label="Proposed Policy")

plt.xlabel("Treatment Action")
plt.ylabel("Frequency")
plt.title("Treatment Distribution Comparison")
plt.legend()

plt.tight_layout()
plt.savefig("figure_action_distribution.pdf", format="pdf")
plt.show()

kl_vals = np.sum(pi_mix * (np.log(pi_mix + 1e-12) - np.log(b_all + 1e-12)), axis=1)

print("Average KL divergence:", kl_vals.mean())
print("Median KL divergence:", np.median(kl_vals))

import pandas as pd

results_table = pd.DataFrame({
    "Metric": ["Clinician (Behavior)", "Proposed Policy (DR)"],
    "Value": [behavior, dr_mean],
    "CI Lower": ["-", ci_low],
    "CI Upper": ["-", ci_high],
    "ESS": ["-", results_correct["ess"]]
})

print(results_table)

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.special import softmax
import zipfile

# -------------------------------
# Creating output directory
# -------------------------------
output_dir = "RLC_results_package"
os.makedirs(output_dir, exist_ok=True)

# -------------------------------
# Clean plotting
# -------------------------------
plt.style.use("seaborn-v0_8-whitegrid")
plt.rcParams.update({
    "figure.figsize": (4.8, 3.6),
    "font.size": 11,
    "axes.titlesize": 12,
    "axes.labelsize": 11,
    "legend.fontsize": 10,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
})

# Color palette (academic clean)
clin_color = "#4C72B0"      # muted blue
policy_color = "#DD8452"    # muted orange

# -------------------------------
# Main DR Performance Plot
# -------------------------------
behavior = results_correct["behavior"]
dr_mean = results_correct["dr"]
ci_low, ci_high = bootstrap_ci(results_correct["DR_vals"], B=1000)

plt.figure()
plt.bar(["Clinician", "Proposed Policy"],
        [behavior, dr_mean],
        color=[clin_color, policy_color])

plt.errorbar(1, dr_mean,
             yerr=[[dr_mean - ci_low], [ci_high - dr_mean]],
             fmt='o', color='black', capsize=4)

plt.ylabel("Expected Discounted Return")
plt.ylim(3.5, 4.2)
plt.title("Performance under Doubly Robust Evaluation")

plt.tight_layout()
plt.savefig(f"{output_dir}/figure_main_performance.pdf", format="pdf")
plt.close()

# -------------------------------
# Subgroup Plot (Baseline Lactate)
# -------------------------------
groups = ["Low Lactate", "High Lactate"]

low_behavior = behavior_vals[low_idx].mean()
high_behavior = behavior_vals[high_idx].mean()
low_dr = DR_vals[low_idx].mean()
high_dr = DR_vals[high_idx].mean()

low_ci = bootstrap_group(DR_vals, low_idx, B=1000)
high_ci = bootstrap_group(DR_vals, high_idx, B=1000)

x = np.arange(len(groups))
width = 0.35

plt.figure()
plt.bar(x - width/2, [low_behavior, high_behavior],
        width, label="Clinician", color=clin_color)

plt.bar(x + width/2, [low_dr, high_dr],
        width, label="Proposed Policy", color=policy_color)

plt.errorbar(x + width/2, [low_dr, high_dr],
             yerr=[np.array([low_dr, high_dr]) - np.array([low_ci[0], high_ci[0]]),
                   np.array([low_ci[1], high_ci[1]]) - np.array([low_dr, high_dr])],
             fmt='o', color='black', capsize=4)

plt.xticks(x, groups)
plt.ylabel("Expected Discounted Return")
plt.ylim(3.4, 4.4)
plt.title("Subgroup Analysis by Baseline Lactate")
plt.legend()

plt.tight_layout()
plt.savefig(f"{output_dir}/figure_subgroup_lactate.pdf", format="pdf")
plt.close()

# -------------------------------
# Treatment Distribution Plot
# -------------------------------
logits = q_all_fqe_correct / 0.5
pi = softmax(logits, axis=1)
pi_mix = (1 - 0.1) * b_all + 0.1 * pi

clin_counts = np.bincount(all_actions)
clin_freq = clin_counts / clin_counts.sum()
policy_freq = pi_mix.mean(axis=0)

x = np.arange(len(clin_freq))

plt.figure()
plt.bar(x - width/2, clin_freq, width,
        label="Clinician", color=clin_color)

plt.bar(x + width/2, policy_freq, width,
        label="Proposed Policy", color=policy_color)

plt.xlabel("Treatment Category")
plt.ylabel("Action Frequency")
plt.title("Treatment Distribution Comparison")
plt.legend()

plt.tight_layout()
plt.savefig(f"{output_dir}/figure_action_distribution.pdf", format="pdf")
plt.close()

# -------------------------------
# Results Table CSV
# -------------------------------
results_table = pd.DataFrame({
    "Policy": ["Clinician", "Proposed Policy"],
    "Return": [behavior, dr_mean],
    "CI_Lower": ["-", ci_low],
    "CI_Upper": ["-", ci_high],
    "ESS": ["-", results_correct["ess"]]
})

results_table.to_csv(f"{output_dir}/results_table.csv", index=False)

# -------------------------------
# KL Divergence
# -------------------------------
kl_vals = np.sum(pi_mix * (np.log(pi_mix + 1e-12) - np.log(b_all + 1e-12)), axis=1)

with open(f"{output_dir}/diagnostics.txt", "w") as f:
    f.write(f"Average KL divergence: {kl_vals.mean()}\n")
    f.write(f"Median KL divergence: {np.median(kl_vals)}\n")
    f.write(f"ESS: {results_correct['ess']}\n")

# -------------------------------
# Zip everything
# -------------------------------
zip_path = "RLC_results_package.zip"
with zipfile.ZipFile(zip_path, 'w') as zipf:
    for file in os.listdir(output_dir):
        zipf.write(os.path.join(output_dir, file),
                   arcname=file)

print("All results saved and zipped.")
print("Download file:", zip_path)

print("Unique actions in dataset:", np.unique(all_actions))
print("Number of unique actions:", len(np.unique(all_actions)))